server:
  port: 80

#logging:
#  level:
#    org.springframework.web: DEBUG
#    reactor.netty.htt: DEBUG

llm:
  ip: 127.0.0.1
  port: 1234

spring:
  data:
    mongodb:
      database: test
      uri: